name: Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
      steps:
        - uses: action/checkout@v2
        - uses: action/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        # setup key
        - run: set -eu
        - run: mkdir "$HOME/.ssh"
        - run: echo "${{ secrets.key }}" > "$HOME/.ssh/MELLO_PRIVATE_KEY"
        - run: chmod 600 "$HOME/.ssh/MELLO_PRIVATE_KEY"
        # build
        - run: npm ci
        - run: npm run build
        # deploy
        - run: cd dist && rsync -e "ssh -i $HOME/.ssh/MELLO_PRIVATE_KEY -0 StrictHostKeyChecking=no" . mello@mello.one:/var/www/mello.one/html
